import type { Metadata } from "next";
import { Card, PageHeader } from "@/components/ui";
import { addDays, todayInColombia } from "@/domain/habits";
import { LifestyleSchema } from "@/domain/lifestyle";
import { deviceHints, OWN_HABITS } from "@/domain/own-habits";
import { deviceSummary } from "@/domain/wearables";
import { requireParticipant } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { LifestyleForm, type OwnPrefill } from "./lifestyle-form";

export const metadata: Metadata = { title: "Empecemos por lo que ya haces" };
// Suggestions are generated by the LLM inside the form's server action.
export const maxDuration = 120;

export default async function StartPage() {
  const { participant: p } = await requireParticipant();
  const supabase = await createClient();
  const today = todayInColombia();
  const [{ data: own }, { data: rows }] = await Promise.all([
    supabase.from("habits").select("title, target_per_week, anchor").eq("participant_id", p.id).eq("source", "own").eq("status", "active"),
    supabase.from("measurements").select("type, value, measured_at, source").eq("participant_id", p.id).in("source", ["strava", "apple_health"]).gte("measured_at", `${addDays(today, -14)}T00:00:00-05:00`),
  ]);
  // Pre-check what they told us before, or else what their watch shows they do.
  const hints = deviceHints(deviceSummary((rows ?? []).map((m) => ({ ...m, value: Number(m.value) })), today, 14));
  const prefill: Record<string, OwnPrefill> = {};
  for (const o of OWN_HABITS) {
    const saved = own?.find((h) => h.title === o.title);
    if (saved) prefill[o.key] = { days: saved.target_per_week, anchor: saved.anchor ?? "" };
    else if (hints[o.key]) prefill[o.key] = { days: hints[o.key].days, anchor: "", why: hints[o.key].why };
  }
  const current = LifestyleSchema.partial().safeParse(p.lifestyle ?? {});
  return (
    <>
      <PageHeader
        title="Empecemos por lo que ya haces"
        subtitle="Primero, lo que ya haces por tu salud: cuenta desde hoy para tu racha. Luego unas preguntas de un toque sobre cómo vives. Solo te sugerimos algo más si vale la pena, y tú decides."
      />
      <Card>
        <LifestyleForm initial={current.success ? current.data : null} goal={p.personal_goal} prefill={prefill} />
      </Card>
    </>
  );
}
