import type { Metadata } from "next";
import { Card, PageHeader } from "@/components/ui";
import { LifestyleSchema } from "@/domain/lifestyle";
import { requireParticipant } from "@/lib/auth";
import { LifestyleForm } from "./lifestyle-form";

export const metadata: Metadata = { title: "Tu plan de hábitos" };
// The plan is generated by the LLM inside the form's server action.
export const maxDuration = 120;

export default async function StartPage() {
  const { participant: p } = await requireParticipant();
  const current = LifestyleSchema.partial().safeParse(p.lifestyle ?? {});
  return (
    <>
      <PageHeader
        title="Armemos tu plan"
        subtitle="Ocho preguntas de un toque sobre cómo vives hoy. Con eso diseñamos hábitos pequeños, anclados a tu rutina, que te acerquen a tu meta. Tus exámenes los afinan después."
      />
      <Card>
        <LifestyleForm initial={current.success ? current.data : null} goal={p.personal_goal} />
      </Card>
    </>
  );
}
