import { BIOMARKERS } from "./biomarkers";

function lit(v: unknown): string {
  if (v === undefined || v === null) return "null";
  if (Array.isArray(v) && v.every((x) => typeof x === "string")) {
    return `array[${v.map((x) => lit(x)).join(", ")}]::text[]`;
  }
  if (typeof v === "object") return `${lit(JSON.stringify(v))}::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
}

/** SQL that upserts the biomarker catalog. Kept in sync by a unit test. */
export function renderBiomarkerSeed(): string {
  const rows = BIOMARKERS.map((b) =>
    `  (${[b.code, b.name, b.category, b.synonyms, b.unit, b.conversions, b.reference, b.optimal ?? null, b.betterWhen, b.source, b.notes ?? null]
      .map(lit)
      .join(", ")})`,
  );
  return `-- GENERATED by scripts/gen-biomarker-seed.ts from src/domain/biomarkers.ts. Do not edit by hand.
insert into public.biomarkers (code, name, category, synonyms, unit, conversions, reference, optimal, better_when, source, notes)
values
${rows.join(",\n")}
on conflict (code) do update set
  name = excluded.name, category = excluded.category, synonyms = excluded.synonyms, unit = excluded.unit,
  conversions = excluded.conversions, reference = excluded.reference, optimal = excluded.optimal,
  better_when = excluded.better_when, source = excluded.source, notes = excluded.notes;
`;
}
