import { readdirSync, readFileSync } from "node:fs";
import path from "node:path";

/** All migrations in order, then the seed, as one script. */
export function renderSetupSql(supabaseDir: string): string {
  const migrations = readdirSync(path.join(supabaseDir, "migrations"))
    .filter((f) => f.endsWith(".sql"))
    .sort();
  const parts = [
    "-- GENERATED by scripts/gen-setup-sql.ts. Paste into Supabase → SQL Editor → Run, once, on a new project.",
    ...migrations.map((f) => `-- ── migrations/${f} ──\n${readFileSync(path.join(supabaseDir, "migrations", f), "utf8")}`),
    `-- ── seed.sql ──\n${readFileSync(path.join(supabaseDir, "seed.sql"), "utf8")}`,
  ];
  return parts.join("\n\n");
}
