-- GENERATED by scripts/gen-setup-sql.ts. Paste into Supabase → SQL Editor → Run, once, on a new project.

-- ── migrations/20260930000100_schema.sql ──
-- Bombadil — core schema.
-- Every table holding participant data has RLS enabled (see 20260930000200_rls.sql).

create extension if not exists pgcrypto;

-- ─── Admins ─────────────────────────────────────────────────────────────────
create table public.admins (
  user_id uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

-- ─── Participants ───────────────────────────────────────────────────────────
create table public.participants (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique references auth.users (id) on delete set null,
  email text not null unique check (email = lower(email)),
  -- Display name is for the operator only; never sent to the LLM.
  display_name text,
  birth_date date,
  sex text check (sex in ('male', 'female')),
  height_cm numeric(5, 1) check (height_cm between 100 and 250),
  personal_goal text check (char_length(personal_goal) <= 1000),
  -- 1-3 current priorities, set by the operator when approving a report.
  priorities text[] not null default '{}' check (cardinality(priorities) <= 3),
  pilot_start date,
  status text not null default 'invited' check (status in ('invited', 'active', 'withdrawn', 'completed')),
  withdrawn_at timestamptz,
  created_at timestamptz not null default now()
);

-- ─── Consents (immutable) ───────────────────────────────────────────────────
create table public.consents (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid not null references public.participants (id) on delete cascade,
  version text not null,
  text_hash text not null,
  accepted_at timestamptz not null default now(),
  user_agent text
);
create index on public.consents (participant_id);

-- ─── Biomarker catalog (seeded from src/domain/biomarkers.ts) ───────────────
create table public.biomarkers (
  code text primary key,
  name text not null,
  category text not null,
  synonyms text[] not null default '{}',
  unit text not null,
  conversions jsonb not null,
  reference jsonb not null,
  optimal jsonb,
  better_when text not null check (better_when in ('lower', 'higher', 'in_range')),
  source text not null,
  notes text
);

-- ─── Lab documents and results ──────────────────────────────────────────────
create table public.lab_documents (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid not null references public.participants (id) on delete cascade,
  storage_path text not null unique,
  original_filename text,
  lab_name text,
  sampled_on date,
  status text not null default 'uploaded'
    check (status in ('uploaded', 'extracting', 'extracted', 'reviewed', 'failed')),
  extraction jsonb,
  extraction_error text,
  prompt_version text,
  model text,
  redactions integer,
  uploaded_by uuid references auth.users (id) on delete set null,
  reviewed_by uuid references auth.users (id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);
create index on public.lab_documents (participant_id);
create index on public.lab_documents (status);

create table public.lab_results (
  id uuid primary key default gen_random_uuid(),
  document_id uuid not null references public.lab_documents (id) on delete cascade,
  participant_id uuid not null references public.participants (id) on delete cascade,
  biomarker_code text not null references public.biomarkers (code),
  sampled_on date not null,
  value_original numeric not null,
  unit_original text not null,
  value_canonical numeric not null,
  lab_ref_low numeric,
  lab_ref_high numeric,
  flag text check (flag in ('low', 'normal', 'high')),
  corrected_by_admin boolean not null default false,
  created_at timestamptz not null default now(),
  unique (document_id, biomarker_code)
);
create index on public.lab_results (participant_id, biomarker_code, sampled_on);

-- ─── Measurements ───────────────────────────────────────────────────────────
create table public.measurements (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid not null references public.participants (id) on delete cascade,
  type text not null check (type in ('weight', 'waist', 'bp_systolic', 'bp_diastolic', 'resting_hr', 'sleep_hours', 'exercise_minutes')),
  value numeric not null,
  unit text not null,
  measured_at timestamptz not null,
  -- {arm: left|right, period: day|night, note}
  context jsonb not null default '{}',
  -- Pairs systolic and diastolic readings taken together.
  group_id uuid,
  -- manual | checkin | abpm | (future) strava | apple_health | garmin
  source text not null default 'manual',
  created_at timestamptz not null default now()
);
create index on public.measurements (participant_id, type, measured_at);

-- ─── Goals ──────────────────────────────────────────────────────────────────
create table public.goals (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid not null references public.participants (id) on delete cascade,
  metric text not null,
  baseline numeric not null,
  target numeric not null,
  horizon_months integer not null check (horizon_months in (3, 6, 12)),
  start_date date not null,
  deadline date not null,
  notes text,
  active boolean not null default true,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  check (deadline > start_date)
);
create index on public.goals (participant_id);

-- ─── Weekly check-ins ───────────────────────────────────────────────────────
create table public.checkins (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid not null references public.participants (id) on delete cascade,
  week integer not null check (week between 1 and 60),
  -- {priority: "done"|"partial"|"no"} per current priority
  adherence jsonb not null default '[]',
  symptoms text[] not null default '{}',
  free_text text check (char_length(free_text) <= 2000),
  answers jsonb not null default '{}',
  duration_seconds integer,
  submitted_at timestamptz not null default now(),
  unique (participant_id, week)
);
create index on public.checkins (participant_id);

-- Replies live apart so participants never see an unapproved draft.
create table public.checkin_replies (
  id uuid primary key default gen_random_uuid(),
  checkin_id uuid not null unique references public.checkins (id) on delete cascade,
  participant_id uuid not null references public.participants (id) on delete cascade,
  draft text,
  final_text text,
  status text not null default 'pending' check (status in ('pending', 'draft', 'failed', 'sent')),
  error text,
  prompt_version text,
  model text,
  sent_by uuid references auth.users (id) on delete set null,
  sent_at timestamptz,
  created_at timestamptz not null default now()
);
create index on public.checkin_replies (status);

-- ─── Reports ────────────────────────────────────────────────────────────────
create table public.reports (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid not null references public.participants (id) on delete cascade,
  content jsonb not null,
  input_snapshot jsonb not null,
  prompt_version text not null,
  model text not null,
  status text not null default 'draft' check (status in ('draft', 'approved', 'archived')),
  approved_by uuid references auth.users (id) on delete set null,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  check (status <> 'approved' or approved_at is not null)
);
create index on public.reports (participant_id, status);

-- ─── Alerts ─────────────────────────────────────────────────────────────────
create table public.alerts (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid not null references public.participants (id) on delete cascade,
  rule_id text not null,
  level text not null check (level in ('urgency', 'consult_soon', 'next_visit')),
  origin text not null check (origin in ('measurement', 'checkin', 'lab')),
  origin_id uuid,
  message text not null,
  evidence text,
  status text not null default 'open' check (status in ('open', 'acknowledged', 'resolved')),
  resolved_by uuid references auth.users (id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);
create index on public.alerts (participant_id, status);

-- ─── Pilot feedback / willingness to pay ────────────────────────────────────
create table public.pilot_feedback (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid not null references public.participants (id) on delete cascade,
  week integer,
  willingness_to_pay_cop integer check (willingness_to_pay_cop >= 0),
  would_continue text check (would_continue in ('yes', 'maybe', 'no')),
  comments text,
  recorded_by uuid references auth.users (id) on delete set null,
  recorded_at timestamptz not null default now()
);
create index on public.pilot_feedback (participant_id);

-- ─── Audit log of admin access (append-only) ────────────────────────────────
create table public.audit_log (
  id bigint generated always as identity primary key,
  actor_user_id uuid not null,
  action text not null,
  participant_id uuid,
  detail jsonb not null default '{}',
  at timestamptz not null default now()
);
create index on public.audit_log (participant_id, at desc);


-- ── migrations/20260930000200_rls.sql ──
-- Bombadil — Row Level Security.
-- Participants see only their own rows; admins see everything.
-- Drafts (reports, check-in replies) are invisible to participants until approved.

-- ─── Helpers ────────────────────────────────────────────────────────────────
create or replace function public.is_admin()
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (select 1 from public.admins where user_id = auth.uid());
$$;

create or replace function public.current_participant_id()
returns uuid
language sql stable security definer set search_path = public
as $$
  select id from public.participants where auth_user_id = auth.uid();
$$;

create or replace function public.is_active_participant()
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (select 1 from public.participants where auth_user_id = auth.uid() and status = 'active');
$$;

-- Link the signed-in user to the participant row the admin created for their email.
create or replace function public.link_participant()
returns uuid
language plpgsql security definer set search_path = public
as $$
declare
  pid uuid;
  mail text := lower(coalesce(auth.jwt() ->> 'email', ''));
begin
  if auth.uid() is null or mail = '' then
    return null;
  end if;
  update public.participants
     set auth_user_id = auth.uid()
   where email = mail and auth_user_id is null
  returning id into pid;
  if pid is null then
    select id into pid from public.participants where auth_user_id = auth.uid();
  end if;
  return pid;
end;
$$;

-- Onboarding: consent + basic data in one transaction. Activates the participant.
create or replace function public.complete_onboarding(
  p_birth_date date,
  p_sex text,
  p_height_cm numeric,
  p_personal_goal text,
  p_consent_version text,
  p_consent_hash text,
  p_user_agent text
)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  pid uuid := public.current_participant_id();
begin
  if pid is null then
    raise exception 'not a participant';
  end if;
  if p_consent_version is null or p_consent_hash is null then
    raise exception 'consent required';
  end if;
  insert into public.consents (participant_id, version, text_hash, user_agent)
  values (pid, p_consent_version, p_consent_hash, left(p_user_agent, 300));
  update public.participants
     set birth_date = p_birth_date,
         sex = p_sex,
         height_cm = p_height_cm,
         personal_goal = p_personal_goal,
         status = case when status = 'invited' then 'active' else status end,
         pilot_start = coalesce(pilot_start, current_date)
   where id = pid;
end;
$$;

-- Participants may edit only their own basic profile fields.
create or replace function public.update_my_profile(p_height_cm numeric, p_personal_goal text)
returns void
language plpgsql security definer set search_path = public
as $$
begin
  update public.participants
     set height_cm = p_height_cm, personal_goal = p_personal_goal
   where id = public.current_participant_id();
end;
$$;

revoke all on function public.link_participant() from public, anon;
revoke all on function public.complete_onboarding(date, text, numeric, text, text, text, text) from public, anon;
revoke all on function public.update_my_profile(numeric, text) from public, anon;
grant execute on function public.link_participant() to authenticated;
grant execute on function public.complete_onboarding(date, text, numeric, text, text, text, text) to authenticated;
grant execute on function public.update_my_profile(numeric, text) to authenticated;

-- ─── Enable RLS everywhere ──────────────────────────────────────────────────
alter table public.admins enable row level security;
alter table public.participants enable row level security;
alter table public.consents enable row level security;
alter table public.biomarkers enable row level security;
alter table public.lab_documents enable row level security;
alter table public.lab_results enable row level security;
alter table public.measurements enable row level security;
alter table public.goals enable row level security;
alter table public.checkins enable row level security;
alter table public.checkin_replies enable row level security;
alter table public.reports enable row level security;
alter table public.alerts enable row level security;
alter table public.pilot_feedback enable row level security;
alter table public.audit_log enable row level security;

-- Nothing is readable anonymously.
revoke all on all tables in schema public from anon;

-- ─── admins ─────────────────────────────────────────────────────────────────
create policy admins_self_read on public.admins for select to authenticated
  using (user_id = auth.uid() or public.is_admin());

-- ─── participants ───────────────────────────────────────────────────────────
create policy participants_read on public.participants for select to authenticated
  using (auth_user_id = auth.uid() or public.is_admin());
create policy participants_admin_write on public.participants for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- ─── consents: insert via complete_onboarding only; read own ────────────────
create policy consents_read on public.consents for select to authenticated
  using (participant_id = public.current_participant_id() or public.is_admin());

-- ─── biomarkers: catalog readable by any signed-in user ─────────────────────
create policy biomarkers_read on public.biomarkers for select to authenticated using (true);
create policy biomarkers_admin_write on public.biomarkers for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- ─── lab_documents: participant uploads & reads own; admin reviews ──────────
create policy lab_documents_read on public.lab_documents for select to authenticated
  using (participant_id = public.current_participant_id() or public.is_admin());
create policy lab_documents_insert_own on public.lab_documents for insert to authenticated
  with check (
    (participant_id = public.current_participant_id() and public.is_active_participant()
      and status = 'uploaded' and extraction is null and reviewed_at is null)
    or public.is_admin()
  );
create policy lab_documents_admin_update on public.lab_documents for update to authenticated
  using (public.is_admin()) with check (public.is_admin());
create policy lab_documents_admin_delete on public.lab_documents for delete to authenticated
  using (public.is_admin());

-- ─── lab_results: only the admin writes (after human review) ────────────────
create policy lab_results_read on public.lab_results for select to authenticated
  using (participant_id = public.current_participant_id() or public.is_admin());
create policy lab_results_admin_write on public.lab_results for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- ─── measurements: participant CRUD own ─────────────────────────────────────
create policy measurements_read on public.measurements for select to authenticated
  using (participant_id = public.current_participant_id() or public.is_admin());
create policy measurements_insert on public.measurements for insert to authenticated
  with check ((participant_id = public.current_participant_id() and public.is_active_participant()) or public.is_admin());
create policy measurements_delete on public.measurements for delete to authenticated
  using (participant_id = public.current_participant_id() or public.is_admin());
create policy measurements_admin_update on public.measurements for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- ─── goals: participant can read and create own; admin all ──────────────────
create policy goals_read on public.goals for select to authenticated
  using (participant_id = public.current_participant_id() or public.is_admin());
create policy goals_insert on public.goals for insert to authenticated
  with check ((participant_id = public.current_participant_id() and public.is_active_participant()) or public.is_admin());
create policy goals_update on public.goals for update to authenticated
  using (participant_id = public.current_participant_id() or public.is_admin())
  with check (participant_id = public.current_participant_id() or public.is_admin());

-- ─── checkins ───────────────────────────────────────────────────────────────
create policy checkins_read on public.checkins for select to authenticated
  using (participant_id = public.current_participant_id() or public.is_admin());
create policy checkins_insert on public.checkins for insert to authenticated
  with check ((participant_id = public.current_participant_id() and public.is_active_participant()) or public.is_admin());
create policy checkins_admin_write on public.checkins for update to authenticated
  using (public.is_admin()) with check (public.is_admin());
create policy checkins_admin_delete on public.checkins for delete to authenticated
  using (public.is_admin());

-- ─── checkin_replies: participant sees only sent replies ────────────────────
create policy checkin_replies_read on public.checkin_replies for select to authenticated
  using ((participant_id = public.current_participant_id() and status = 'sent') or public.is_admin());
create policy checkin_replies_admin_write on public.checkin_replies for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- ─── reports: participant sees only approved ────────────────────────────────
create policy reports_read on public.reports for select to authenticated
  using ((participant_id = public.current_participant_id() and status = 'approved') or public.is_admin());
create policy reports_admin_write on public.reports for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- ─── alerts: participants may raise (not edit) their own ────────────────────
create policy alerts_read on public.alerts for select to authenticated
  using (participant_id = public.current_participant_id() or public.is_admin());
create policy alerts_insert on public.alerts for insert to authenticated
  with check ((participant_id = public.current_participant_id() and status = 'open') or public.is_admin());
create policy alerts_admin_update on public.alerts for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- ─── pilot_feedback ─────────────────────────────────────────────────────────
create policy pilot_feedback_read on public.pilot_feedback for select to authenticated
  using (participant_id = public.current_participant_id() or public.is_admin());
create policy pilot_feedback_insert on public.pilot_feedback for insert to authenticated
  with check (participant_id = public.current_participant_id() or public.is_admin());
create policy pilot_feedback_admin_write on public.pilot_feedback for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- ─── audit_log: admins append as themselves; read by admins; never edited ───
create policy audit_insert on public.audit_log for insert to authenticated
  with check (public.is_admin() and actor_user_id = auth.uid());
create policy audit_read on public.audit_log for select to authenticated
  using (public.is_admin());


-- ── migrations/20260930000300_storage.sql ──
-- Private bucket for lab PDFs. Paths: {participant_id}/{uuid}.pdf
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('lab-pdfs', 'lab-pdfs', false, 15728640, array['application/pdf'])
on conflict (id) do nothing;

create policy lab_pdfs_insert_own on storage.objects for insert to authenticated
  with check (
    bucket_id = 'lab-pdfs'
    and (storage.foldername(name))[1] = public.current_participant_id()::text
    and public.is_active_participant()
  );

create policy lab_pdfs_read on storage.objects for select to authenticated
  using (
    bucket_id = 'lab-pdfs'
    and ((storage.foldername(name))[1] = public.current_participant_id()::text or public.is_admin())
  );

create policy lab_pdfs_admin_all on storage.objects for all to authenticated
  using (bucket_id = 'lab-pdfs' and public.is_admin())
  with check (bucket_id = 'lab-pdfs' and public.is_admin());


-- ── migrations/20261001000100_longevity_levers.sql ──
-- Longevity levers from the evidence review (docs: "Longevidad: base de evidencia para Bombadil"):
-- grip strength, estimated VO2max and weekly alcohol as measurements; smoking status on the profile.

-- ─── Measurements: new types ────────────────────────────────────────────────
alter table public.measurements drop constraint measurements_type_check;
alter table public.measurements add constraint measurements_type_check check (type in (
  'weight', 'waist', 'bp_systolic', 'bp_diastolic', 'resting_hr', 'sleep_hours', 'exercise_minutes',
  'grip_strength', 'vo2max', 'alcohol_drinks'
));

-- ─── Participants: smoking status ───────────────────────────────────────────
alter table public.participants
  add column smoking_status text check (smoking_status in ('never', 'former', 'current'));

-- ─── Onboarding and profile RPCs take the smoking status ────────────────────
drop function public.complete_onboarding(date, text, numeric, text, text, text, text);
create function public.complete_onboarding(
  p_birth_date date,
  p_sex text,
  p_height_cm numeric,
  p_personal_goal text,
  p_smoking_status text,
  p_consent_version text,
  p_consent_hash text,
  p_user_agent text
)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  pid uuid := public.current_participant_id();
begin
  if pid is null then
    raise exception 'not a participant';
  end if;
  if p_consent_version is null or p_consent_hash is null then
    raise exception 'consent required';
  end if;
  insert into public.consents (participant_id, version, text_hash, user_agent)
  values (pid, p_consent_version, p_consent_hash, left(p_user_agent, 300));
  update public.participants
     set birth_date = p_birth_date,
         sex = p_sex,
         height_cm = p_height_cm,
         personal_goal = p_personal_goal,
         smoking_status = p_smoking_status,
         status = case when status = 'invited' then 'active' else status end,
         pilot_start = coalesce(pilot_start, current_date)
   where id = pid;
end;
$$;

drop function public.update_my_profile(numeric, text);
create function public.update_my_profile(p_height_cm numeric, p_personal_goal text, p_smoking_status text)
returns void
language plpgsql security definer set search_path = public
as $$
begin
  update public.participants
     set height_cm = p_height_cm, personal_goal = p_personal_goal, smoking_status = p_smoking_status
   where id = public.current_participant_id();
end;
$$;

revoke all on function public.complete_onboarding(date, text, numeric, text, text, text, text, text) from public, anon;
revoke all on function public.update_my_profile(numeric, text, text) from public, anon;
grant execute on function public.complete_onboarding(date, text, numeric, text, text, text, text, text) to authenticated;
grant execute on function public.update_my_profile(numeric, text, text) to authenticated;


-- ── seed.sql ──
-- GENERATED by scripts/gen-biomarker-seed.ts from src/domain/biomarkers.ts. Do not edit by hand.
insert into public.biomarkers (code, name, category, synonyms, unit, conversions, reference, optimal, better_when, source, notes)
values
  ('glucose_fasting', 'Glucosa en ayunas', 'glucose', array['glucosa', 'glicemia', 'glucemia', 'glicemia basal', 'glucosa basal', 'glucosa en suero', 'glucose']::text[], 'mg/dL', '[{"unit":"mg/dl","factor":1},{"unit":"mmol/l","factor":18.016}]'::jsonb, '{"low":70,"high":99}'::jsonb, '{"low":70,"high":90}'::jsonb, 'in_range', 'Referencia: ADA Standards of Care 2025 (100–125 = prediabetes). Óptimo: criterio conservador, PENDIENTE DE VALIDAR con médico asesor.', null),
  ('hba1c', 'Hemoglobina glicosilada (HbA1c)', 'glucose', array['hba1c', 'hemoglobina glicosilada', 'hemoglobina glucosilada', 'a1c', 'hemoglobina a1c']::text[], '%', '[{"unit":"%","factor":1},{"unit":"mmol/mol","factor":0.09148,"offset":2.152}]'::jsonb, '{"high":5.6}'::jsonb, '{"high":5.4}'::jsonb, 'lower', 'Referencia: ADA 2025 (5.7–6.4 % prediabetes, ≥6.5 % diabetes). Óptimo: PENDIENTE DE VALIDAR con médico asesor.', null),
  ('total_cholesterol', 'Colesterol total', 'lipids', array['colesterol total', 'colesterol', 'cholesterol total', 'ct']::text[], 'mg/dL', '[{"unit":"mg/dl","factor":1},{"unit":"mmol/l","factor":38.67}]'::jsonb, '{"high":199}'::jsonb, '{"high":180}'::jsonb, 'lower', 'Referencia: NCEP ATP III (<200 mg/dL deseable). Óptimo: PENDIENTE DE VALIDAR con médico asesor.', null),
  ('ldl', 'Colesterol LDL', 'lipids', array['ldl', 'colesterol ldl', 'c-ldl', 'ldl colesterol', 'colesterol de baja densidad', 'ldl directo', 'ldl calculado']::text[], 'mg/dL', '[{"unit":"mg/dl","factor":1},{"unit":"mmol/l","factor":38.67}]'::jsonb, '{"high":129}'::jsonb, '{"high":99}'::jsonb, 'lower', 'NCEP ATP III: <100 óptimo, 100–129 cercano a óptimo, 130–159 limítrofe, ≥190 muy alto.', null),
  ('hdl', 'Colesterol HDL', 'lipids', array['hdl', 'colesterol hdl', 'c-hdl', 'hdl colesterol', 'colesterol de alta densidad']::text[], 'mg/dL', '[{"unit":"mg/dl","factor":1},{"unit":"mmol/l","factor":38.67}]'::jsonb, '{"male":{"low":40},"female":{"low":50}}'::jsonb, '{"low":60}'::jsonb, 'higher', 'NCEP ATP III / IDF: bajo <40 (hombres) o <50 (mujeres); ≥60 protector.', null),
  ('triglycerides', 'Triglicéridos', 'lipids', array['trigliceridos', 'triglicéridos', 'tg', 'triglycerides']::text[], 'mg/dL', '[{"unit":"mg/dl","factor":1},{"unit":"mmol/l","factor":88.57}]'::jsonb, '{"high":149}'::jsonb, '{"high":99}'::jsonb, 'lower', 'NCEP ATP III (<150 normal). Óptimo <100: AHA Scientific Statement on Triglycerides (Miller et al., 2011).', null),
  ('apob', 'Apolipoproteína B (ApoB)', 'lipids', array['apob', 'apo b', 'apolipoproteina b', 'apolipoproteína b', 'apolipoproteina b100', 'apo b-100', 'apolipoprotein b']::text[], 'mg/dL', '[{"unit":"mg/dl","factor":1},{"unit":"g/l","factor":100}]'::jsonb, '{"high":119}'::jsonb, '{"high":89}'::jsonb, 'lower', 'Cuenta las partículas aterogénicas; mejor marcador de riesgo que el LDL cuando no coinciden. Metas ESC/EAS 2019: <100 mg/dL riesgo moderado, <80 alto, <65 muy alto. Referencia y óptimo: PENDIENTE DE VALIDAR con médico asesor.', null),
  ('lpa', 'Lipoproteína(a) — Lp(a)', 'lipids', array['lp(a)', 'lpa', 'lipoproteina a', 'lipoproteína a', 'lipoproteina (a)', 'lipoproteína (a)', 'lipoprotein(a)']::text[], 'mg/dL', '[{"unit":"mg/dl","factor":1},{"unit":"nmol/l","factor":0.465}]'::jsonb, '{"high":49}'::jsonb, '{"high":29}'::jsonb, 'lower', 'Mayormente genética; basta medirla una vez en la vida. Consenso EAS 2022: >50 mg/dL (~105 nmol/L) aumenta el riesgo cardiovascular, <30 mg/dL lo descarta. PENDIENTE DE VALIDAR con médico asesor.', 'La conversión desde nmol/L es aproximada.'),
  ('ast', 'AST (TGO)', 'liver', array['ast', 'tgo', 'transaminasa oxalacetica', 'transaminasa glutamico oxalacetica', 'aspartato aminotransferasa', 'sgot']::text[], 'U/L', '[{"unit":"u/l","factor":1}]'::jsonb, '{"high":40}'::jsonb, '{"high":30}'::jsonb, 'lower', 'Referencia: rango típico de laboratorio (preferir el del informe). Óptimo: PENDIENTE DE VALIDAR con médico asesor.', null),
  ('alt', 'ALT (TGP)', 'liver', array['alt', 'tgp', 'transaminasa piruvica', 'transaminasa glutamico piruvica', 'alanina aminotransferasa', 'sgpt']::text[], 'U/L', '[{"unit":"u/l","factor":1}]'::jsonb, '{"high":40}'::jsonb, '{"male":{"high":33},"female":{"high":25}}'::jsonb, 'lower', 'Referencia: rango típico de laboratorio. Óptimo: ACG Clinical Guideline (Kwo et al., 2017) — ALT normal 29–33 U/L hombres, 19–25 U/L mujeres.', null),
  ('ggt', 'Gamma glutamil transferasa (GGT)', 'liver', array['ggt', 'gamma gt', 'gamma glutamil transferasa', 'gamma glutamil transpeptidasa', 'ggtp']::text[], 'U/L', '[{"unit":"u/l","factor":1}]'::jsonb, '{"male":{"high":60},"female":{"high":40}}'::jsonb, '{"high":30}'::jsonb, 'lower', 'Referencia: rango típico de laboratorio. Óptimo: PENDIENTE DE VALIDAR con médico asesor.', null),
  ('creatinine', 'Creatinina', 'kidney', array['creatinina', 'creatinina en suero', 'creatinina serica', 'creatinine']::text[], 'mg/dL', '[{"unit":"mg/dl","factor":1},{"unit":"umol/l","factor":0.011309658448314861}]'::jsonb, '{"male":{"low":0.7,"high":1.3},"female":{"low":0.6,"high":1.1}}'::jsonb, null, 'in_range', 'Rango típico de laboratorio. Interpretar junto con TFG estimada (KDIGO 2024).', null),
  ('bun', 'Nitrógeno ureico (BUN)', 'kidney', array['bun', 'nitrogeno ureico', 'nitrógeno ureico', 'nitrogeno ureico en suero', 'urea']::text[], 'mg/dL', '[{"unit":"mg/dl","factor":1},{"unit":"mmol/l","factor":2.801},{"unit":"mg/dl(urea)","factor":0.4672897196261682}]'::jsonb, '{"low":7,"high":20}'::jsonb, null, 'in_range', 'Rango típico de laboratorio.', 'Si el informe reporta ''Urea'' en mg/dL, la extracción usa la unidad ''mg/dL (urea)'' para convertir a BUN.'),
  ('uric_acid', 'Ácido úrico', 'kidney', array['acido urico', 'ácido úrico', 'uric acid']::text[], 'mg/dL', '[{"unit":"mg/dl","factor":1},{"unit":"umol/l","factor":0.016812373907195696}]'::jsonb, '{"male":{"low":3.4,"high":7},"female":{"low":2.4,"high":6}}'::jsonb, '{"high":6}'::jsonb, 'lower', 'Referencia: rango típico. Óptimo <6: objetivo de EULAR 2016 para gota, PENDIENTE DE VALIDAR con médico asesor.', null),
  ('tsh', 'TSH', 'thyroid', array['tsh', 'hormona estimulante de tiroides', 'tirotropina', 'tsh ultrasensible', 'hormona estimulante del tiroides']::text[], 'mUI/L', '[{"unit":"mu/l","factor":1}]'::jsonb, '{"low":0.4,"high":4}'::jsonb, null, 'in_range', 'American Thyroid Association: 0.4–4.0 mUI/L (varía con edad y laboratorio).', null),
  ('vitamin_d', 'Vitamina D (25-OH)', 'vitamins', array['vitamina d', '25 oh vitamina d', '25-hidroxivitamina d', '25(oh)d', 'vitamina d total', 'vitamina d 25 hidroxi']::text[], 'ng/mL', '[{"unit":"ng/ml","factor":1},{"unit":"nmol/l","factor":0.40064102564102566}]'::jsonb, '{"low":30,"high":100}'::jsonb, '{"low":30,"high":60}'::jsonb, 'in_range', 'Endocrine Society 2011 (≥30 suficiente; <20 deficiencia). La guía 2024 no recomienda tamizaje rutinario. Óptimo: PENDIENTE DE VALIDAR con médico asesor.', null),
  ('vitamin_b12', 'Vitamina B12', 'vitamins', array['vitamina b12', 'b12', 'cobalamina', 'cianocobalamina']::text[], 'pg/mL', '[{"unit":"pg/ml","factor":1},{"unit":"pmol/l","factor":1.355},{"unit":"ng/l","factor":1}]'::jsonb, '{"low":200,"high":900}'::jsonb, '{"low":400}'::jsonb, 'in_range', 'Referencia: rango típico (<200 deficiencia). Óptimo: PENDIENTE DE VALIDAR con médico asesor.', null),
  ('hemoglobin', 'Hemoglobina', 'blood_count', array['hemoglobina', 'hb', 'hgb', 'hemoglobin']::text[], 'g/dL', '[{"unit":"g/dl","factor":1},{"unit":"g/l","factor":0.1},{"unit":"mmol/l","factor":1.611}]'::jsonb, '{"male":{"low":13.5,"high":17.5},"female":{"low":12,"high":15.5}}'::jsonb, null, 'in_range', 'Rango típico de laboratorio; OMS define anemia <13 (hombres) y <12 (mujeres).', 'En altura (p. ej. Bogotá, ~2.600 m) la OMS ajusta los puntos de corte hacia arriba. PENDIENTE decidir si se aplica el ajuste.'),
  ('hematocrit', 'Hematocrito', 'blood_count', array['hematocrito', 'hto', 'hct', 'hematocrit']::text[], '%', '[{"unit":"%","factor":1},{"unit":"l/l","factor":100}]'::jsonb, '{"male":{"low":41,"high":53},"female":{"low":36,"high":46}}'::jsonb, null, 'in_range', 'Rango típico de laboratorio (nivel del mar).', null),
  ('platelets', 'Plaquetas', 'blood_count', array['plaquetas', 'recuento de plaquetas', 'plt', 'platelets']::text[], '10³/µL', '[{"unit":"10^3/ul","factor":1},{"unit":"/ul","factor":0.001}]'::jsonb, '{"low":150,"high":450}'::jsonb, null, 'in_range', 'Rango típico de laboratorio.', null),
  ('wbc', 'Leucocitos', 'blood_count', array['leucocitos', 'recuento de leucocitos', 'globulos blancos', 'glóbulos blancos', 'wbc', 'recuento de globulos blancos']::text[], '10³/µL', '[{"unit":"10^3/ul","factor":1},{"unit":"/ul","factor":0.001}]'::jsonb, '{"low":4,"high":11}'::jsonb, null, 'in_range', 'Rango típico de laboratorio.', null),
  ('eosinophils_pct', 'Eosinófilos (%)', 'blood_count', array['eosinofilos %', 'eosinófilos %', 'eosinofilos porcentaje', 'eos %']::text[], '%', '[{"unit":"%","factor":1}]'::jsonb, '{"low":0,"high":6}'::jsonb, null, 'in_range', 'Rango típico de laboratorio.', null),
  ('eosinophils_abs', 'Eosinófilos (absolutos)', 'blood_count', array['eosinofilos #', 'eosinófilos absolutos', 'eosinofilos absolutos', 'recuento de eosinofilos', 'eos #']::text[], '10³/µL', '[{"unit":"10^3/ul","factor":1},{"unit":"/ul","factor":0.001}]'::jsonb, '{"low":0,"high":0.5}'::jsonb, null, 'in_range', 'Rango típico de laboratorio (>0.5 ×10³/µL = eosinofilia).', null),
  ('hscrp', 'PCR ultrasensible', 'inflammation', array['pcr ultrasensible', 'proteina c reactiva ultrasensible', 'pcr-us', 'hs-crp', 'pcr alta sensibilidad']::text[], 'mg/L', '[{"unit":"mg/l","factor":1},{"unit":"mg/dl","factor":10}]'::jsonb, '{"high":3}'::jsonb, '{"high":1}'::jsonb, 'lower', 'AHA/CDC 2003 (Pearson et al.): <1 riesgo bajo, 1–3 promedio, >3 alto. >10 sugiere proceso agudo.', null),
  ('uacr', 'Microalbuminuria (relación albúmina/creatinina)', 'kidney', array['microalbuminuria', 'relacion albumina creatinina', 'relación albúmina/creatinina', 'rac', 'uacr', 'albumina en orina']::text[], 'mg/g', '[{"unit":"mg/g","factor":1},{"unit":"ug/mg","factor":1},{"unit":"mg/mmol","factor":8.84}]'::jsonb, '{"high":29}'::jsonb, '{"high":10}'::jsonb, 'lower', 'KDIGO 2024: A1 <30, A2 30–300, A3 >300 mg/g. Óptimo: PENDIENTE DE VALIDAR con médico asesor.', 'Si el laboratorio solo reporta concentración (mg/L) no es comparable: el admin debe anotarlo.')
on conflict (code) do update set
  name = excluded.name, category = excluded.category, synonyms = excluded.synonyms, unit = excluded.unit,
  conversions = excluded.conversions, reference = excluded.reference, optimal = excluded.optimal,
  better_when = excluded.better_when, source = excluded.source, notes = excluded.notes;
